name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          for proj in $(find AtelierTomato.Soil -type f -name '*.csproj'); do
            dotnet restore "$proj"
          done

      - name: Build
        run: |
          for proj in $(find AtelierTomato.Soil -type f -name '*.csproj'); do
            dotnet build "$proj" --configuration Release --no-restore
          done

      - name: Pack
        run: |
          for proj in $(find AtelierTomato.Soil -type f -name '*.csproj'); do
            dotnet pack "$proj" --configuration Release --no-build
          done

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget push AtelierTomato.Soil/**/*.nupkg --source "https://nuget.pkg.github.com/OWNER/index.json"

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push AtelierTomato.Soil/**/*.nupkg --source "https://api.nuget.org/v3/index.json"
